### ISSUE TITLE
Using this package in a non-organization account 

### ISSUE THREAD

**Issue by jelledv** [get-select/dbt-snowflake-monitoring#85]
Hello, 

I am trying to use this package from an account that is not the organization account and thus a sub account. In your sources, you define a source that looks at the organization_usage schema. The ORGANIZATION_USAGE schema is only available from an account that has the [ORGADMIN role enabled](https://docs.snowflake.com/en/user-guide/organizations-gs.html#label-enabling-orgadmin-role-for-account) (i.e. the ORGADMIN account). Any idea if it is possible and how I can give access to this schema? 

Currently the dbt run succeeds, but the organization views return an empty result, resulting in an empty dbt_queries view

```
  - name: snowflake_organization_usage
    database: snowflake
    schema: organization_usage
    tables:
      - name: rate_sheet_daily
      - name: remaining_balance_daily
```
